name: neweramuseum_
favicon: null
layout_spectrum: 0.3627546741627157
typography_spectrum: 0.6106779554393142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9105410049669445
  lightness: 0.42602084251120687
  saturation: 0.737029260257259
  rhythmicContrast: 0.5896784435026348
purpose: []
